/*
 * title
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GetSamplePoint -
func GetSamplePoint(c *gin.Context) {
	var (
		entity = SampleResponseStreamOf()
	)
	entity.
		AddAll(
			SampleResponse{"1"},
			SampleResponse{"2"},
			SampleResponse{"3"},
		)
	c.JSON(http.StatusOK, entity)
}
